In [4]:
import torch
import torch.nn.functional as F


In [5]:
tensor = torch.tensor([1.11, 2.22,3.33])

In [6]:
print(tensor)
print(f"size : {tensor.shape}")

tensor([1.1100, 2.2200, 3.3300])
size : torch.Size([3])


In [7]:
# Unsqueeze (-1)
tensor_usq = tensor.unsqueeze(-1)
print(tensor_usq)
print(f"size : {tensor_usq.shape}")

tensor([[1.1100],
        [2.2200],
        [3.3300]])
size : torch.Size([3, 1])


In [8]:

tensor_usq0 = tensor.unsqueeze(0)
print(tensor_usq0)

tensor([[1.1100, 2.2200, 3.3300]])


In [9]:
tensor_usq1 = tensor.unsqueeze(1)
print(tensor_usq1)

tensor([[1.1100],
        [2.2200],
        [3.3300]])


In [10]:
tensor_view = tensor.view(3,1,1)
print(tensor_view)

tensor([[[1.1100]],

        [[2.2200]],

        [[3.3300]]])


In [11]:
double_usq = tensor.unsqueeze(-1).unsqueeze(-1)
print(double_usq)

tensor([[[1.1100]],

        [[2.2200]],

        [[3.3300]]])


In [12]:
sift_feature = 5
cluster = 3
my_rand = torch.rand(cluster, sift_feature)

In [13]:
my_rand

tensor([[7.2815e-01, 1.5869e-01, 1.4870e-02, 8.7533e-01, 1.5603e-01],
        [8.9327e-01, 6.3838e-01, 6.6284e-01, 8.2633e-02, 3.2932e-01],
        [7.4492e-01, 2.0105e-04, 8.8861e-01, 1.4424e-04, 5.6391e-01]])

In [14]:
mb = my_rand.unsqueeze(-1)
print(mb)
print(mb.size())

tensor([[[7.2815e-01],
         [1.5869e-01],
         [1.4870e-02],
         [8.7533e-01],
         [1.5603e-01]],

        [[8.9327e-01],
         [6.3838e-01],
         [6.6284e-01],
         [8.2633e-02],
         [3.2932e-01]],

        [[7.4492e-01],
         [2.0105e-04],
         [8.8861e-01],
         [1.4424e-04],
         [5.6391e-01]]])
torch.Size([3, 5, 1])


In [15]:
mbb = my_rand.unsqueeze(-1).unsqueeze(-1)
print(mbb)
print(mbb.size())

tensor([[[[7.2815e-01]],

         [[1.5869e-01]],

         [[1.4870e-02]],

         [[8.7533e-01]],

         [[1.5603e-01]]],


        [[[8.9327e-01]],

         [[6.3838e-01]],

         [[6.6284e-01]],

         [[8.2633e-02]],

         [[3.2932e-01]]],


        [[[7.4492e-01]],

         [[2.0105e-04]],

         [[8.8861e-01]],

         [[1.4424e-04]],

         [[5.6391e-01]]]])
torch.Size([3, 5, 1, 1])


In [16]:
import torchinfo
from torchvision.models import resnet18
import torch.nn as nn
import torch.nn.functional as F

In [17]:
encoder = resnet18(pretrained=True)
base_model = nn.Sequential(
    encoder.conv1,
    encoder.bn1,
    encoder.relu,
    encoder.maxpool,
    encoder.layer1,
    encoder.layer2,
    encoder.layer3,
    encoder.layer4,
)

/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:04<00:00, 11.6MB/s]


In [18]:
dim = list(base_model.parameters())[-1].shape # last channels (512)
print(dim)


torch.Size([512])


In [19]:
torchinfo.summary(base_model.cuda(), input_size=(1,3,128,128))

/usr/local/lib/python3.8/dist-packages/torchinfo/torchinfo.py:477: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  action_fn=lambda data: sys.getsizeof(data.storage()),
/usr/local/lib/python3.8/dist-packages/torch/storage.py:665: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return super().__sizeof__() + self.nbytes()


Layer (type:depth-idx)                   Output Shape              Param #
Sequential                               [1, 512, 4, 4]            --
├─Conv2d: 1-1                            [1, 64, 64, 64]           9,408
├─BatchNorm2d: 1-2                       [1, 64, 64, 64]           128
├─ReLU: 1-3                              [1, 64, 64, 64]           --
├─MaxPool2d: 1-4                         [1, 64, 32, 32]           --
├─Sequential: 1-5                        [1, 64, 32, 32]           --
│    └─BasicBlock: 2-1                   [1, 64, 32, 32]           --
│    │    └─Conv2d: 3-1                  [1, 64, 32, 32]           36,864
│    │    └─BatchNorm2d: 3-2             [1, 64, 32, 32]           128
│    │    └─ReLU: 3-3                    [1, 64, 32, 32]           --
│    │    └─Conv2d: 3-4                  [1, 64, 32, 32]           36,864
│    │    └─BatchNorm2d: 3-5             [1, 64, 32, 32]           128
│    │    └─ReLU: 3-6                    [1, 64, 32, 32]           --
│

In [20]:
[1,512,4,4][0:2]

[1, 512]

In [21]:
new = torch.rand(1,512,4,4)
print(new.view(1,512,-1).shape)

torch.Size([1, 512, 16])


In [22]:
my_conv = nn.Conv2d(
            512, 
            6, 
            kernel_size=(1, 1), 
            bias=True
        )

In [23]:
import torchinfo

In [24]:
torchinfo.summary(my_conv.cuda(), input_size=(1,512,4,4))

Layer (type:depth-idx)                   Output Shape              Param #
Conv2d                                   [1, 6, 4, 4]              3,078
Total params: 3,078
Trainable params: 3,078
Non-trainable params: 0
Total mult-adds (M): 0.05
Input size (MB): 0.03
Forward/backward pass size (MB): 0.00
Params size (MB): 0.01
Estimated Total Size (MB): 0.05

In [25]:
ss = torch.rand(1,6,4,4).view(1,6,-1)
print(ss)

tensor([[[0.7852, 0.5784, 0.1528, 0.4612, 0.7106, 0.5171, 0.8022, 0.5683,
          0.7150, 0.1212, 0.4636, 0.8589, 0.5574, 0.8001, 0.0434, 0.2428],
         [0.9871, 0.6572, 0.7927, 0.8297, 0.9227, 0.6970, 0.4442, 0.6385,
          0.2318, 0.9802, 0.3872, 0.2767, 0.4034, 0.8627, 0.9311, 0.5454],
         [0.0037, 0.0264, 0.3679, 0.9835, 0.1493, 0.4445, 0.0636, 0.9144,
          0.8475, 0.0130, 0.5486, 0.5653, 0.5115, 0.3440, 0.8899, 0.7220],
         [0.9174, 0.0590, 0.3086, 0.2512, 0.4556, 0.5660, 0.3144, 0.1915,
          0.4945, 0.5386, 0.8707, 0.0412, 0.9870, 0.0501, 0.2896, 0.1599],
         [0.2586, 0.3623, 0.6896, 0.8461, 0.9263, 0.3250, 0.3942, 0.6331,
          0.8401, 0.4188, 0.1729, 0.2023, 0.7900, 0.3431, 0.9115, 0.6900],
         [0.6423, 0.7802, 0.9591, 0.6700, 0.8479, 0.6112, 0.4812, 0.1818,
          0.0136, 0.6040, 0.6598, 0.5944, 0.3216, 0.4885, 0.9683, 0.4388]]])


In [26]:
ss.shape

torch.Size([1, 6, 16])

In [27]:
ss.size(-1)

16

In [28]:
F.softmax(ss, dim=0)

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [29]:
sss = F.softmax(ss, dim=1)

In [30]:
sss

tensor([[[0.1894, 0.1893, 0.1081, 0.1308, 0.1675, 0.1639, 0.2392, 0.1690,
          0.1927, 0.1144, 0.1543, 0.2480, 0.1562, 0.2205, 0.0837, 0.1304],
         [0.2318, 0.2049, 0.2049, 0.1891, 0.2071, 0.1962, 0.1672, 0.1812,
          0.1188, 0.2700, 0.1429, 0.1386, 0.1339, 0.2347, 0.2034, 0.1765],
         [0.0867, 0.1090, 0.1340, 0.2206, 0.0956, 0.1524, 0.1143, 0.2388,
          0.2200, 0.1026, 0.1680, 0.1849, 0.1492, 0.1397, 0.1952, 0.2106],
         [0.2161, 0.1126, 0.1263, 0.1060, 0.1298, 0.1721, 0.1468, 0.1159,
          0.1546, 0.1736, 0.2318, 0.1095, 0.2401, 0.1041, 0.1071, 0.1200],
         [0.1119, 0.1525, 0.1848, 0.1922, 0.2078, 0.1353, 0.1590, 0.1803,
          0.2184, 0.1540, 0.1154, 0.1286, 0.1971, 0.1396, 0.1995, 0.2039],
         [0.1642, 0.2317, 0.2420, 0.1612, 0.1922, 0.1801, 0.1735, 0.1148,
          0.0955, 0.1853, 0.1877, 0.1904, 0.1234, 0.1614, 0.2111, 0.1586]]])

In [31]:
bb = torch.tensor([
    [[1,2,3]],
    [[4,5,6]]
],dtype=float)
print(bb)
print(bb.shape)

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]], dtype=torch.float64)
torch.Size([2, 1, 3])


In [32]:
F.softmax(ss, dim=1)

tensor([[[0.1894, 0.1893, 0.1081, 0.1308, 0.1675, 0.1639, 0.2392, 0.1690,
          0.1927, 0.1144, 0.1543, 0.2480, 0.1562, 0.2205, 0.0837, 0.1304],
         [0.2318, 0.2049, 0.2049, 0.1891, 0.2071, 0.1962, 0.1672, 0.1812,
          0.1188, 0.2700, 0.1429, 0.1386, 0.1339, 0.2347, 0.2034, 0.1765],
         [0.0867, 0.1090, 0.1340, 0.2206, 0.0956, 0.1524, 0.1143, 0.2388,
          0.2200, 0.1026, 0.1680, 0.1849, 0.1492, 0.1397, 0.1952, 0.2106],
         [0.2161, 0.1126, 0.1263, 0.1060, 0.1298, 0.1721, 0.1468, 0.1159,
          0.1546, 0.1736, 0.2318, 0.1095, 0.2401, 0.1041, 0.1071, 0.1200],
         [0.1119, 0.1525, 0.1848, 0.1922, 0.2078, 0.1353, 0.1590, 0.1803,
          0.2184, 0.1540, 0.1154, 0.1286, 0.1971, 0.1396, 0.1995, 0.2039],
         [0.1642, 0.2317, 0.2420, 0.1612, 0.1922, 0.1801, 0.1735, 0.1148,
          0.0955, 0.1853, 0.1877, 0.1904, 0.1234, 0.1614, 0.2111, 0.1586]]])

In [33]:
0.0900+0.2447+0.6652

0.9999

In [34]:
class NetVLAD(nn.Module):
    """NetVLAD layer implementation"""

    def __init__(self, num_clusters=64, dim=128, 
                 normalize_input=True, vladv2=False):
        """
        Args:
            num_clusters : int
                The number of clusters
            dim : int
                Dimension of descriptors
            alpha : float
                Parameter of initialization. Larger value is harder assignment.
            normalize_input : bool
                If true, descriptor-wise L2 normalization is applied to input.
            vladv2 : bool
                If true, use vladv2 otherwise use vladv1
        """
        super(NetVLAD, self).__init__()
        self.num_clusters = num_clusters
        self.dim = dim
        self.alpha = 0
        self.vladv2 = vladv2
        self.normalize_input = normalize_input
        self.conv = nn.Conv2d(dim, num_clusters, kernel_size=(1, 1), bias=vladv2)
        self.centroids = nn.Parameter(torch.rand(num_clusters, dim))

    def init_params(self, clsts, traindescs):
        #TODO replace numpy ops with pytorch ops
        if self.vladv2 == False:
            clstsAssign = clsts / np.linalg.norm(clsts, axis=1, keepdims=True)
            dots = np.dot(clstsAssign, traindescs.T)
            dots.sort(0)
            dots = dots[::-1, :] # sort, descending

            self.alpha = (-np.log(0.01) / np.mean(dots[0,:] - dots[1,:])).item()
            self.centroids = nn.Parameter(torch.from_numpy(clsts))
            self.conv.weight = nn.Parameter(torch.from_numpy(self.alpha*clstsAssign).unsqueeze(2).unsqueeze(3))
            self.conv.bias = None
       

    def forward(self, x):
        N, C = x.shape[:2]

        if self.normalize_input:
            x = F.normalize(x, p=2, dim=1)  # across descriptor dim

        # soft-assignment
        soft_assign = self.conv(x).view(N, self.num_clusters, -1)
        soft_assign = F.softmax(soft_assign, dim=1)

        x_flatten = x.view(N, C, -1)
        
        # calculate residuals to each clusters
        vlad = torch.zeros([N, self.num_clusters, C], dtype=x.dtype, layout=x.layout, device=x.device)
        for C in range(self.num_clusters): # slower than non-looped, but lower memory usage 
            residual = x_flatten.unsqueeze(0).permute(1, 0, 2, 3) - \
                    self.centroids[C:C+1, :].expand(x_flatten.size(-1), -1, -1).permute(1, 2, 0).unsqueeze(0)
            residual *= soft_assign[:,C:C+1,:].unsqueeze(2)
            vlad[:,C:C+1,:] = residual.sum(dim=-1)

        vlad = F.normalize(vlad, p=2, dim=2)  # intra-normalization
        vlad = vlad.view(x.size(0), -1)  # flatten
        vlad = F.normalize(vlad, p=2, dim=1)  # L2 normalize

        return vlad

In [35]:
model_netvlad = NetVLAD(6,128,100,True)


In [36]:
torchinfo.summary(model_netvlad, input_size=(1,128,4,4))

Layer (type:depth-idx)                   Output Shape              Param #
NetVLAD                                  [1, 768]                  768
├─Conv2d: 1-1                            [1, 6, 4, 4]              774
Total params: 1,542
Trainable params: 1,542
Non-trainable params: 0
Total mult-adds (M): 0.01
Input size (MB): 0.01
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01

In [37]:
entries = 5
embedded_dim = 3
embeddings = torch.rand(entries, embedded_dim) * 100e-2

In [38]:
embeddings

tensor([[0.6352, 0.5320, 0.7064],
        [0.7644, 0.1169, 0.4576],
        [0.2635, 0.0951, 0.7375],
        [0.5630, 0.0347, 0.9274],
        [0.6348, 0.9995, 0.1905]])

In [39]:
!nvidia-smi

Sun May 21 11:06:26 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090         Off| 00000000:03:00.0 Off |                  N/A |
|  0%   42C    P2              107W / 420W|    514MiB / 24576MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [40]:
def _pairwise_distance(x, squared=False, eps=1e-16):
    # Compute the 2D matrix of distances between all the embeddings.

    cor_mat = torch.matmul(x, x.t())
    print("Correlation Matrix : \n{}".format(cor_mat))
    norm_mat = cor_mat.diag()
    print("Norm Matrix : \n{}".format(norm_mat))
    print("NORM UNSQUEEZE(0) : \n{}".format(norm_mat.unsqueeze(0)))
    print("NORM UNSQUEEZE(1) : \n{}".format(norm_mat.unsqueeze(1)))
    
    print("2xCorMat : \n{}".format(2 * cor_mat))
    print("NormMat.UQ(1) Minus 2xCorMat : \n{}".format(norm_mat.unsqueeze(1) - 2 * cor_mat))
    distances = norm_mat.unsqueeze(1) - 2 * cor_mat + norm_mat.unsqueeze(0)
    print("Dist Matrix before relu : \n{}".format(distances))
    
    distances = F.relu(distances)
    print("Dist Matrix After relu : \n{}".format(distances))
    
    ccc = torch.sqrt(distances)
    
    if not squared:
        mask = torch.eq(distances, 0.0).float()
        print("Mask : \n{}".format(mask))
        
        distances = distances + mask * eps
        print("Distance After +Mask : \n{}".format(distances))
        
        distances = torch.sqrt(distances)
        distances = distances * (1.0 - mask)
        
        print("EQ : \n{}".format(torch.eq(distances, ccc)))

    return distances

In [41]:
_pairwise_distance(embeddings)

Correlation Matrix : 
tensor([[1.1855, 0.8709, 0.7389, 1.0312, 1.0696],
        [0.8709, 0.8073, 0.5500, 0.8588, 0.6893],
        [0.7389, 0.5500, 0.6223, 0.8356, 0.4028],
        [1.0312, 0.8588, 0.8356, 1.1783, 0.5688],
        [1.0696, 0.6893, 0.4028, 0.5688, 1.4383]])
Norm Matrix : 
tensor([1.1855, 0.8073, 0.6223, 1.1783, 1.4383])
NORM UNSQUEEZE(0) : 
tensor([[1.1855, 0.8073, 0.6223, 1.1783, 1.4383]])
NORM UNSQUEEZE(1) : 
tensor([[1.1855],
        [0.8073],
        [0.6223],
        [1.1783],
        [1.4383]])
2xCorMat : 
tensor([[2.3710, 1.7419, 1.4778, 2.0624, 2.1391],
        [1.7419, 1.6147, 1.0999, 1.7175, 1.3786],
        [1.4778, 1.0999, 1.2446, 1.6711, 0.8057],
        [2.0624, 1.7175, 1.6711, 2.3566, 1.1376],
        [2.1391, 1.3786, 0.8057, 1.1376, 2.8765]])
NormMat.UQ(1) Minus 2xCorMat : 
tensor([[-1.1855, -0.5564, -0.2923, -0.8769, -0.9536],
        [-0.9346, -0.8073, -0.2926, -0.9102, -0.5713],
        [-0.8555, -0.4776, -0.6223, -1.0488, -0.1833],
        [-0.8841, -

tensor([[0.0000, 0.5009, 0.5745, 0.5490, 0.6962],
        [0.5009, 0.0000, 0.5742, 0.5178, 0.9311],
        [0.5745, 0.5742, 0.0000, 0.3598, 1.1202],
        [0.5490, 0.5178, 0.3598, 0.0000, 1.2161],
        [0.6962, 0.9311, 1.1202, 1.2161, 0.0000]])

In [42]:
_pairwise_distance(embeddings)[0:1,]

Correlation Matrix : 
tensor([[1.1855, 0.8709, 0.7389, 1.0312, 1.0696],
        [0.8709, 0.8073, 0.5500, 0.8588, 0.6893],
        [0.7389, 0.5500, 0.6223, 0.8356, 0.4028],
        [1.0312, 0.8588, 0.8356, 1.1783, 0.5688],
        [1.0696, 0.6893, 0.4028, 0.5688, 1.4383]])
Norm Matrix : 
tensor([1.1855, 0.8073, 0.6223, 1.1783, 1.4383])
NORM UNSQUEEZE(0) : 
tensor([[1.1855, 0.8073, 0.6223, 1.1783, 1.4383]])
NORM UNSQUEEZE(1) : 
tensor([[1.1855],
        [0.8073],
        [0.6223],
        [1.1783],
        [1.4383]])
2xCorMat : 
tensor([[2.3710, 1.7419, 1.4778, 2.0624, 2.1391],
        [1.7419, 1.6147, 1.0999, 1.7175, 1.3786],
        [1.4778, 1.0999, 1.2446, 1.6711, 0.8057],
        [2.0624, 1.7175, 1.6711, 2.3566, 1.1376],
        [2.1391, 1.3786, 0.8057, 1.1376, 2.8765]])
NormMat.UQ(1) Minus 2xCorMat : 
tensor([[-1.1855, -0.5564, -0.2923, -0.8769, -0.9536],
        [-0.9346, -0.8073, -0.2926, -0.9102, -0.5713],
        [-0.8555, -0.4776, -0.6223, -1.0488, -0.1833],
        [-0.8841, -

tensor([[0.0000, 0.5009, 0.5745, 0.5490, 0.6962]])

In [43]:
import numpy as np

In [44]:
a = np.array(embeddings[0].cpu())
b = np.array(embeddings[1].cpu())
c = a-b

In [45]:
c

array([-0.12922621,  0.41509724,  0.24882591], dtype=float32)

In [46]:
np.sum(c)

0.53469694

In [47]:
np.sum(np.abs(c))

0.79314935

In [48]:
np.power(c,2)

array([0.01669941, 0.17230572, 0.06191433], dtype=float32)

In [49]:
np.sqrt(np.sum(np.square(c)))

0.5009186

In [50]:
a1 = torch.rand(5,1)
a1

tensor([[0.7849],
        [0.5271],
        [0.4303],
        [0.1717],
        [0.1719]])

In [51]:
a2 = torch.rand(5,5)
a2

tensor([[0.7946, 0.9408, 0.3434, 0.6827, 0.3488],
        [0.0984, 0.2320, 0.1589, 0.5463, 0.3872],
        [0.7900, 0.1299, 0.1952, 0.1102, 0.0526],
        [0.9526, 0.6893, 0.6370, 0.3693, 0.9401],
        [0.2349, 0.0320, 0.8531, 0.6454, 0.3235]])

In [52]:
a1+a2

tensor([[1.5795, 1.7257, 1.1283, 1.4676, 1.1336],
        [0.6255, 0.7591, 0.6860, 1.0734, 0.9143],
        [1.2203, 0.5601, 0.6255, 0.5405, 0.4829],
        [1.1242, 0.8610, 0.8087, 0.5410, 1.1118],
        [0.4068, 0.2039, 1.0250, 0.8173, 0.4953]])

In [53]:
a2

tensor([[0.7946, 0.9408, 0.3434, 0.6827, 0.3488],
        [0.0984, 0.2320, 0.1589, 0.5463, 0.3872],
        [0.7900, 0.1299, 0.1952, 0.1102, 0.0526],
        [0.9526, 0.6893, 0.6370, 0.3693, 0.9401],
        [0.2349, 0.0320, 0.8531, 0.6454, 0.3235]])

In [54]:
a3 = a2 - a2.diag()
a3 = F.relu(a3)
a3

tensor([[0.0000, 0.7088, 0.1482, 0.3134, 0.0253],
        [0.0000, 0.0000, 0.0000, 0.1769, 0.0637],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1580, 0.4573, 0.4418, 0.0000, 0.6166],
        [0.0000, 0.0000, 0.6579, 0.2761, 0.0000]])

In [55]:
mask = torch.eq(a3, 0.0).float()
mask

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 0.],
        [1., 1., 0., 0., 1.]])

In [56]:
a4 = a3 + mask*1e-16
a4

tensor([[1.0000e-16, 7.0877e-01, 1.4818e-01, 3.1340e-01, 2.5292e-02],
        [1.0000e-16, 1.0000e-16, 1.0000e-16, 1.7693e-01, 6.3727e-02],
        [1.0000e-16, 1.0000e-16, 1.0000e-16, 1.0000e-16, 1.0000e-16],
        [1.5797e-01, 4.5728e-01, 4.4182e-01, 1.0000e-16, 6.1661e-01],
        [1.0000e-16, 1.0000e-16, 6.5794e-01, 2.7612e-01, 1.0000e-16]])

In [57]:
a5 = torch.sqrt(a4)
a5

tensor([[1.0000e-08, 8.4188e-01, 3.8494e-01, 5.5982e-01, 1.5903e-01],
        [1.0000e-08, 1.0000e-08, 1.0000e-08, 4.2063e-01, 2.5244e-01],
        [1.0000e-08, 1.0000e-08, 1.0000e-08, 1.0000e-08, 1.0000e-08],
        [3.9746e-01, 6.7622e-01, 6.6470e-01, 1.0000e-08, 7.8524e-01],
        [1.0000e-08, 1.0000e-08, 8.1114e-01, 5.2548e-01, 1.0000e-08]])

In [58]:
(1.0 - mask)

tensor([[0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 1.],
        [0., 0., 1., 1., 0.]])

In [59]:
a6 = a5 * (1.0 - mask)
a6

tensor([[0.0000, 0.8419, 0.3849, 0.5598, 0.1590],
        [0.0000, 0.0000, 0.0000, 0.4206, 0.2524],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3975, 0.6762, 0.6647, 0.0000, 0.7852],
        [0.0000, 0.0000, 0.8111, 0.5255, 0.0000]])

In [60]:
ss = torch.zeros(5,5)
ss

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [61]:
torch.sqrt(ss)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [62]:
torch.sqrt(torch.zeros(1))

tensor([0.])

In [63]:
labels = torch.tensor([1,1,2,2,3,3,3,1,1])
labels

tensor([1, 1, 2, 2, 3, 3, 3, 1, 1])

In [64]:
def _get_anchor_positive_triplet_mask(labels):
    """
    Given labels of size (batch_size, ) 
    Return a 2D Mask : Where mask[Anchor, Positive] is True
    iff Anchor and Positive 
    - Distinct 
    - Same Label
    
    Mask will omitted the self index (result 0)
    label [1,1,2,2,3,1] 
    for item idx 0 will return [X(zero),1,0,0,0,1]
    """
    # Device Select
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    # Negative Mask
    indices_not_equal = torch.eye(labels.shape[0]).to(device).byte() ^ 1

    # Check if labels[i] == labels[j]
    labels_equal = torch.unsqueeze(labels, 0) == torch.unsqueeze(labels, 1)
    
    mask = indices_not_equal * labels_equal

    return mask

In [65]:
_get_anchor_positive_triplet_mask(labels)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
def _get_anchor_negative_triplet_mask(labels):
    # Return a 2D mask where mask[a, n] is True iff a and n have distinct labels.

    # Check if labels[i] != labels[k]
    labels_equal = torch.unsqueeze(labels, 0) == torch.unsqueeze(labels, 1)
    mask = labels_equal ^ 1

    return mask

In [ ]:
_get_anchor_negative_triplet_mask(labels)

In [69]:
pd = torch.rand(2,2)
pd

tensor([[0.1414, 0.3443],
        [0.8465, 0.2429]])

In [74]:
u0 = pd.unsqueeze(dim=0)
print(u0)
print(u0.shape)

tensor([[[0.1414, 0.3443],
         [0.8465, 0.2429]]])
torch.Size([1, 2, 2])


In [75]:
u1 = pd.unsqueeze(dim=1)
print(u1)
print(u1.shape)

tensor([[[0.1414, 0.3443]],

        [[0.8465, 0.2429]]])
torch.Size([2, 1, 2])


In [76]:
u2 = pd.unsqueeze(dim=2)
print(u2)
print(u2.shape)

tensor([[[0.1414],
         [0.3443]],

        [[0.8465],
         [0.2429]]])
torch.Size([2, 2, 1])
