In [1]:
import torch


In [7]:
tensor = torch.tensor([1.11, 2.22,3.33])

In [8]:
print(tensor)
print(f"size : {tensor.shape}")

tensor([1.1100, 2.2200, 3.3300])
size : torch.Size([3])


In [9]:
# Unsqueeze (-1)
tensor_usq = tensor.unsqueeze(-1)
print(tensor_usq)
print(f"size : {tensor_usq.shape}")

tensor([[1.1100],
        [2.2200],
        [3.3300]])
size : torch.Size([3, 1])


In [11]:

tensor_usq0 = tensor.unsqueeze(0)
print(tensor_usq0)

tensor([[1.1100, 2.2200, 3.3300]])


In [12]:
tensor_usq1 = tensor.unsqueeze(1)
print(tensor_usq1)

tensor([[1.1100],
        [2.2200],
        [3.3300]])


In [14]:
tensor_view = tensor.view(3,1,1)
print(tensor_view)

tensor([[[1.1100]],

        [[2.2200]],

        [[3.3300]]])


In [15]:
double_usq = tensor.unsqueeze(-1).unsqueeze(-1)
print(double_usq)

tensor([[[1.1100]],

        [[2.2200]],

        [[3.3300]]])


In [4]:
sift_feature = 5
cluster = 3
my_rand = torch.rand(cluster, sift_feature)

In [5]:
my_rand

tensor([[0.1376, 0.6032, 0.4464, 0.7913, 0.2872],
        [0.8638, 0.1759, 0.9549, 0.6871, 0.1608],
        [0.8741, 0.9658, 0.2262, 0.7003, 0.7457]])

In [8]:
mb = my_rand.unsqueeze(-1)
print(mb)
print(mb.size())

tensor([[[0.1376],
         [0.6032],
         [0.4464],
         [0.7913],
         [0.2872]],

        [[0.8638],
         [0.1759],
         [0.9549],
         [0.6871],
         [0.1608]],

        [[0.8741],
         [0.9658],
         [0.2262],
         [0.7003],
         [0.7457]]])
torch.Size([3, 5, 1])


In [9]:
mbb = my_rand.unsqueeze(-1).unsqueeze(-1)
print(mbb)
print(mbb.size())

tensor([[[[0.1376]],

         [[0.6032]],

         [[0.4464]],

         [[0.7913]],

         [[0.2872]]],


        [[[0.8638]],

         [[0.1759]],

         [[0.9549]],

         [[0.6871]],

         [[0.1608]]],


        [[[0.8741]],

         [[0.9658]],

         [[0.2262]],

         [[0.7003]],

         [[0.7457]]]])
torch.Size([3, 5, 1, 1])


In [60]:
import torchinfo
from torchvision.models import resnet18
import torch.nn as nn
import torch.nn.functional as F

In [61]:
encoder = resnet18(pretrained=True)
base_model = nn.Sequential(
    encoder.conv1,
    encoder.bn1,
    encoder.relu,
    encoder.maxpool,
    encoder.layer1,
    encoder.layer2,
    encoder.layer3,
    encoder.layer4,
)

/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [62]:
dim = list(base_model.parameters())[-1].shape # last channels (512)
print(dim)


torch.Size([512])


In [63]:
torchinfo.summary(base_model.cuda(), input_size=(1,3,128,128))

Layer (type:depth-idx)                   Output Shape              Param #
Sequential                               [1, 512, 4, 4]            --
├─Conv2d: 1-1                            [1, 64, 64, 64]           9,408
├─BatchNorm2d: 1-2                       [1, 64, 64, 64]           128
├─ReLU: 1-3                              [1, 64, 64, 64]           --
├─MaxPool2d: 1-4                         [1, 64, 32, 32]           --
├─Sequential: 1-5                        [1, 64, 32, 32]           --
│    └─BasicBlock: 2-1                   [1, 64, 32, 32]           --
│    │    └─Conv2d: 3-1                  [1, 64, 32, 32]           36,864
│    │    └─BatchNorm2d: 3-2             [1, 64, 32, 32]           128
│    │    └─ReLU: 3-3                    [1, 64, 32, 32]           --
│    │    └─Conv2d: 3-4                  [1, 64, 32, 32]           36,864
│    │    └─BatchNorm2d: 3-5             [1, 64, 32, 32]           128
│    │    └─ReLU: 3-6                    [1, 64, 32, 32]           --
│

In [64]:
[1,512,4,4][0:2]

[1, 512]

In [65]:
new = torch.rand(1,512,4,4)
print(new.view(1,512,-1).shape)

torch.Size([1, 512, 16])


In [66]:
my_conv = nn.Conv2d(
            512, 
            6, 
            kernel_size=(1, 1), 
            bias=True
        )

In [67]:
import torchinfo

In [68]:
torchinfo.summary(my_conv.cuda(), input_size=(1,512,4,4))

Layer (type:depth-idx)                   Output Shape              Param #
Conv2d                                   [1, 6, 4, 4]              3,078
Total params: 3,078
Trainable params: 3,078
Non-trainable params: 0
Total mult-adds (M): 0.05
Input size (MB): 0.03
Forward/backward pass size (MB): 0.00
Params size (MB): 0.01
Estimated Total Size (MB): 0.05

In [81]:
ss = torch.rand(1,6,4,4).view(1,6,-1)
print(ss)

tensor([[[0.7807, 0.6215, 0.6427, 0.4053, 0.3169, 0.6360, 0.6230, 0.7028,
          0.8886, 0.2784, 0.1953, 0.0918, 0.0181, 0.9317, 0.8835, 0.3831],
         [0.5167, 0.1571, 0.5845, 0.2236, 0.7641, 0.5312, 0.0935, 0.3518,
          0.0795, 0.3420, 0.0050, 0.3177, 0.7047, 0.6678, 0.6314, 0.5727],
         [0.5590, 0.9872, 0.9179, 0.9304, 0.1583, 0.8918, 0.6423, 0.3031,
          0.6654, 0.0754, 0.7955, 0.7830, 0.4375, 0.6081, 0.5205, 0.3352],
         [0.6074, 0.2962, 0.8822, 0.0391, 0.2883, 0.7607, 0.3719, 0.2519,
          0.3320, 0.8926, 0.5397, 0.0525, 0.8153, 0.3484, 0.1667, 0.9284],
         [0.4017, 0.0116, 0.1207, 0.8514, 0.9456, 0.7708, 0.6621, 0.7564,
          0.8200, 0.4606, 0.6318, 0.6606, 0.0234, 0.4841, 0.4219, 0.3614],
         [0.3547, 0.4958, 0.3930, 0.3433, 0.8997, 0.8088, 0.1566, 0.8244,
          0.0740, 0.3304, 0.9534, 0.5310, 0.9969, 0.8270, 0.9054, 0.8407]]])


In [97]:
ss.shape

torch.Size([1, 6, 16])

In [98]:
ss.size(-1)

16

In [96]:
F.softmax(ss, dim=0)

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [82]:
sss = F.softmax(ss, dim=1)

In [83]:
sss

tensor([[[0.2106, 0.1917, 0.1694, 0.1488, 0.1241, 0.1502, 0.1979, 0.1925,
          0.2384, 0.1432, 0.1144, 0.1173, 0.0962, 0.2179, 0.2167, 0.1343],
         [0.1618, 0.1205, 0.1598, 0.1241, 0.1942, 0.1353, 0.1165, 0.1355,
          0.1061, 0.1526, 0.0946, 0.1470, 0.1912, 0.1673, 0.1685, 0.1623],
         [0.1687, 0.2763, 0.2231, 0.2516, 0.1059, 0.1940, 0.2017, 0.1290,
          0.1907, 0.1169, 0.2085, 0.2340, 0.1463, 0.1577, 0.1508, 0.1280],
         [0.1771, 0.1384, 0.2152, 0.1032, 0.1206, 0.1702, 0.1539, 0.1226,
          0.1366, 0.2646, 0.1614, 0.1127, 0.2135, 0.1216, 0.1058, 0.2317],
         [0.1442, 0.1041, 0.1005, 0.2325, 0.2328, 0.1719, 0.2058, 0.2031,
          0.2226, 0.1718, 0.1770, 0.2071, 0.0967, 0.1393, 0.1366, 0.1314],
         [0.1376, 0.1690, 0.1320, 0.1399, 0.2223, 0.1785, 0.1241, 0.2174,
          0.1056, 0.1508, 0.2441, 0.1819, 0.2560, 0.1962, 0.2216, 0.2122]]])

In [95]:
bb = torch.tensor([
    [[1,2,3]],
    [[4,5,6]]
],dtype=float)
print(bb)
print(bb.shape)

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]], dtype=torch.float64)
torch.Size([2, 1, 3])


In [93]:
F.softmax(ss, dim=1)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]], dtype=torch.float64)

In [94]:
0.0900+0.2447+0.6652

0.9999

In [105]:
class NetVLAD(nn.Module):
    """NetVLAD layer implementation"""

    def __init__(self, num_clusters=64, dim=128, 
                 normalize_input=True, vladv2=False):
        """
        Args:
            num_clusters : int
                The number of clusters
            dim : int
                Dimension of descriptors
            alpha : float
                Parameter of initialization. Larger value is harder assignment.
            normalize_input : bool
                If true, descriptor-wise L2 normalization is applied to input.
            vladv2 : bool
                If true, use vladv2 otherwise use vladv1
        """
        super(NetVLAD, self).__init__()
        self.num_clusters = num_clusters
        self.dim = dim
        self.alpha = 0
        self.vladv2 = vladv2
        self.normalize_input = normalize_input
        self.conv = nn.Conv2d(dim, num_clusters, kernel_size=(1, 1), bias=vladv2)
        self.centroids = nn.Parameter(torch.rand(num_clusters, dim))

    def init_params(self, clsts, traindescs):
        #TODO replace numpy ops with pytorch ops
        if self.vladv2 == False:
            clstsAssign = clsts / np.linalg.norm(clsts, axis=1, keepdims=True)
            dots = np.dot(clstsAssign, traindescs.T)
            dots.sort(0)
            dots = dots[::-1, :] # sort, descending

            self.alpha = (-np.log(0.01) / np.mean(dots[0,:] - dots[1,:])).item()
            self.centroids = nn.Parameter(torch.from_numpy(clsts))
            self.conv.weight = nn.Parameter(torch.from_numpy(self.alpha*clstsAssign).unsqueeze(2).unsqueeze(3))
            self.conv.bias = None
       

    def forward(self, x):
        N, C = x.shape[:2]

        if self.normalize_input:
            x = F.normalize(x, p=2, dim=1)  # across descriptor dim

        # soft-assignment
        soft_assign = self.conv(x).view(N, self.num_clusters, -1)
        soft_assign = F.softmax(soft_assign, dim=1)

        x_flatten = x.view(N, C, -1)
        
        # calculate residuals to each clusters
        vlad = torch.zeros([N, self.num_clusters, C], dtype=x.dtype, layout=x.layout, device=x.device)
        for C in range(self.num_clusters): # slower than non-looped, but lower memory usage 
            residual = x_flatten.unsqueeze(0).permute(1, 0, 2, 3) - \
                    self.centroids[C:C+1, :].expand(x_flatten.size(-1), -1, -1).permute(1, 2, 0).unsqueeze(0)
            residual *= soft_assign[:,C:C+1,:].unsqueeze(2)
            vlad[:,C:C+1,:] = residual.sum(dim=-1)

        vlad = F.normalize(vlad, p=2, dim=2)  # intra-normalization
        vlad = vlad.view(x.size(0), -1)  # flatten
        vlad = F.normalize(vlad, p=2, dim=1)  # L2 normalize

        return vlad

In [106]:
model_netvlad = NetVLAD(6,128,100,True)


In [107]:
torchinfo.summary(model_netvlad, input_size=(1,128,4,4))

Layer (type:depth-idx)                   Output Shape              Param #
NetVLAD                                  [1, 768]                  768
├─Conv2d: 1-1                            [1, 6, 4, 4]              774
Total params: 1,542
Trainable params: 1,542
Non-trainable params: 0
Total mult-adds (M): 0.01
Input size (MB): 0.01
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01